package com.ssm.entity;

public class College {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeID
     *
     * @mbggenerated
     */
    private Integer collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeName
     *
     * @mbggenerated
     */
    private String collegeName;

    public Integer getCollegeId() {
		return collegeId;
	}

	public void setCollegeId(Integer collegeId) {
		this.collegeId = collegeId;
	}

	public String getCollegeName() {
		return collegeName;
	}

	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	@Override
	public String toString() {
		return "College [collegeId=" + collegeId + ", collegeName=" + collegeName + "]";
	}

	
	
}