package com.ssm.entity;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseID
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacherID
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseTime
     *
     * @mbggenerated
     */
    private String courseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.classRoom
     *
     * @mbggenerated
     */
    private String classRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseWeek
     *
     * @mbggenerated
     */
    private Integer courseWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseType
     *
     * @mbggenerated
     */
    private String courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.collegeID
     *
     * @mbggenerated
     */
    private Integer collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.score
     *
     * @mbggenerated
     */
    private Integer score;

	public Integer getCourseId() {
		return courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Integer getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public String getCourseTime() {
		return courseTime;
	}

	public void setCourseTime(String courseTime) {
		this.courseTime = courseTime;
	}

	public String getClassRoom() {
		return classRoom;
	}

	public void setClassRoom(String classRoom) {
		this.classRoom = classRoom;
	}

	public Integer getCourseWeek() {
		return courseWeek;
	}

	public void setCourseWeek(Integer courseWeek) {
		this.courseWeek = courseWeek;
	}

	public String getCourseType() {
		return courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	public Integer getCollegeId() {
		return collegeId;
	}

	public void setCollegeId(Integer collegeId) {
		this.collegeId = collegeId;
	}

	public Integer getScore() {
		return score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}


   
    
}