package com.ssm.dao;

import com.ssm.entity.Userlogin;

public interface UserloginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    int deleteByName(String userName);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbggenerated
     */
    int insert(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbggenerated
     */
    int insertSelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbggenerated
     */
    Userlogin selectByPrimaryKey(Integer userid);

    Userlogin selectByName(String name);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userlogin record);
}